### ISSUE TITLE
Error: spawn openssl ENOENT

### ISSUE THREAD

**Issue by xeroxstar** [codevibess/openssl-nodejs#2]
The module do not work on my end, not sure what does it mean but i get this error.

events.js:174
      throw er; // Unhandled 'error' event
      ^

```
Error: spawn openssl ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by codevibess** [comment]
Hi Vadim, 

I have tasted openssl-nodejs, and I don`t find any problems in the workflow.
Can you give me more information about what command you want to run  what was pasted and what the type of param (just a simple _string_ or _raw data_) . 
It can help me to simulate the situation and find out what was wrong.

Regards, 
Andrii

**Comment by xeroxstar** [comment]
After playing with it, i successfully installed it. Thank you.

**Comment by Angramme** [comment]
Hi, what did you do to fix the error. I get the exact same one as you did. Do you have to install openssl cli for openssl-nodejs to work? or is it built in?

**Comment by iolarha** [comment]
> After playing with it, i successfully installed it. Thank you.

Hi, how did you fix it? I've got the same error

**Comment by liaokuan4hub** [comment]
> After playing with it, i successfully installed it. Thank you.
Hi, I get the same error as you did, what did you do to fix the error? thank you.

**Comment by tshiamor-adft** [comment]
@xeroxstar any details on how this was fixed? facing the same problem on windows. just tried running a minimal example from the readme provided.

**Comment by codevibess** [comment]
Hi @Angramme  @tshiamor-adft , just make sure, that command what you try to invoke is correct (try in a terminal window)
If it doesn't solve your problem, please give me more information about the command that you trying to run. As I said above When I tested it I don`t find any problems in the workflow.

Sincerely, 
Andrii

**Comment by tshiamor-adft** [comment]
Hi @codevibess , thanks for the reply. I first tried the examples in the readme, i.e 
```
openssl('openssl req -config csr.cnf -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout key.key -out certificate.crt')
```
and got the same error as above,  then figured there might be some changes on how some parameters are passed such as the "rsa:2048". 

 So on terminal this command is confirmed working however it fails when using the library

![image](https://user-images.githubusercontent.com/38854734/73440294-fea59100-438b-11ea-8ea2-581452fbc1ff.png)

then the same command i tried:
![image](https://user-images.githubusercontent.com/38854734/73440514-5a701a00-438c-11ea-824e-d9e906e70238.png)
response when running :
![image](https://user-images.githubusercontent.com/38854734/73440769-dd917000-438c-11ea-95d8-80ff3ca940a0.png)

**Comment by codevibess** [comment]
@tshiamor-adft I tested all commands from a readme in Windows 10, macOS, Centos with different node versions, but I don't get the same error.

If about your peace of code:

I have noticed a bug/non covered use case in my code that can cause this behavior.
As I said in the README file: 

> When you used a command which generates additional output in file format this package will create a folder openssl/ in the directory where the command was invoked. All output files will appear in this folder (openssl).

But it creates a folder only when you use the _Buffer_ parameter.

For example: 
_Code:_ 
```
const openssl = require("openssl-nodejs")

openssl('openssl genpkey -out privkey.pem -algorithm RSA -pkeyopt rsa_keygen_bits:2018 -pkeyopt rsa_keygen_pubexp:3', (output) => console.log(output.toString()));
```
_Output:_ 
```
OpenSSL process ends with code 1
Can't open output file openssl/privkey.pem
```
**Why?** 
Because the library trying to write a file in a non-existing directory (_openssl_. This directory will be automatically created only with Buffer parameter use case). 

**Workaround:**
Try to escape from this directory using a relative path. For your use case it will look like this: 
```
const openssl = require("openssl-nodejs")

openssl('openssl genpkey -out ../privkey.pem -algorithm RSA -pkeyopt rsa_keygen_bits:2018 -pkeyopt rsa_keygen_pubexp:3', (output) => console.log(output.toString()));
```
As you see I add a **../** to output private key. (for non-buffer command invocation which generates output to files use directory escaping).

**About unhandled exception**:
As soon as I find the root cause of it it will be fixed.

**Summary**
I will cover it in README or change the behavior of a package as soon as possible. 
But before that, I need to analyze the impact of possible changes and decide which way is better. 

But anyway for anyone who is faced with the same problem it can be a temporal workaround.

@tshiamor-adft Please try code written above.

**Comment by tshiamor-adft** [comment]
thanks again @codevibess ,I tried the minimal code on a few windows computers, not sure if im missing something because I still get the same error even when running the updated command i.e:

```
const openssl = require("openssl-nodejs")

openssl('openssl genpkey -out ../privkey.pem -algorithm RSA -pkeyopt rsa_keygen_bits:2018 -pkeyopt rsa_keygen_pubexp:3', (output) => console.log(output.toString()));
```

**Comment by tshiamor-adft** [comment]
its fine now, i suppose its more of an installation issue, likely that the terminal window did not have its system variables updated, with the openssl.exe path. got fixed when i ran the code from a different terminal.

**Comment by Moises-dev08** [comment]
> thanks again @codevibess ,I tried the minimal code on a few windows computers, not sure if im missing something because I still get the same error even when running the updated command i.e:
> 
> ```
> const openssl = require("openssl-nodejs")
> 
> openssl('openssl genpkey -out ../privkey.pem -algorithm RSA -pkeyopt rsa_keygen_bits:2018 -pkeyopt rsa_keygen_pubexp:3', (output) => console.log(output.toString()));
> ```

Hi, where did you paste this code? Thanks

**Comment by ksw25** [comment]
How to specify where to read the file from? 
No matter what I do, the path for the file always starts on `openssl/` directory.

Example: 
`openssl('openssl x509 -noout -text -in ../certs/ca-g3.pem', (output) => console.log(output.toString()));`

Error:
```{
    "errorType": "Error",
    "errorMessage": "spawn openssl ENOENT",
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn openssl",
    "path": "openssl",
    "spawnargs": [
        "x509",
        "-noout",
        "-text",
        "-in",
        "openssl/../certs/ca-g3.pem"
    ],
    "stack": [
        "Error: spawn openssl ENOENT",
        "    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)",
        "    at onErrorNT (internal/child_process.js:470:16)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}
```

**Comment by Coldplayer1995** [comment]
Why is this closed if that has not been fixed? I am having the same difficulties to run this.
